[project]
name = "query"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
query = "query:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
